name: Build iOS (Kyra)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-13

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Flutter manually
        run: |
          git clone https://github.com/flutter/flutter.git -b stable
          echo "$PWD/flutter/bin" >> $GITHUB_PATH
          flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS (no codesign)
        run: flutter build ios --no-codesign

